import type { PrioritizationItem } from './types';
import { createPrioritizationItemId } from '../../contracts/prioritizationIds';

const MOCK_PRIORITIZATION_DATE = '2026-04-14';

export const createMockPrioritizationItems = (): PrioritizationItem[] => [
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'open_pa_follow_up',
      'employee',
      'Maria Lopez',
    ),
    itemType: 'employee',
    priorityBucket: 'open_pa_follow_up',
    displayLabel: 'Maria Lopez - open PA follow-up',
    employeeName: 'Maria Lopez',
    employeeId: 'EMP-1042',
    stationName: null,
    stationId: null,
    sourceReason:
      'Open physical assessment follow-up from yesterday for shoulder discomfort after pallet wrapping.',
    relatedEncounterType: 'PA Follow-Ups',
    relatedAssessmentType: 'Physical Assessment',
    dueDate: '2026-04-14',
    status: 'open',
    notes: 'Reconnect before second break and confirm whether symptoms changed overnight.',
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'worker_not_yet_encountered',
      'employee',
      'James Turner',
    ),
    itemType: 'employee',
    priorityBucket: 'worker_not_yet_encountered',
    displayLabel: 'James Turner - first encounter still needed',
    employeeName: 'James Turner',
    employeeId: 'EMP-1180',
    stationName: null,
    stationId: null,
    sourceReason: 'Assigned to Line 4 today with no encounter completed yet.',
    relatedEncounterType: 'Relationship Development',
    relatedAssessmentType: null,
    dueDate: null,
    status: 'open',
    notes: null,
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'worker_uncertain_pain_discomfort',
      'employee',
      'Ashley Kim',
    ),
    itemType: 'employee',
    priorityBucket: 'worker_uncertain_pain_discomfort',
    displayLabel: 'Ashley Kim - discomfort still uncertain',
    employeeName: 'Ashley Kim',
    employeeId: 'EMP-1207',
    stationName: null,
    stationId: null,
    sourceReason:
      'Worker mentioned possible soreness near end of shift but discomfort was not confirmed.',
    relatedEncounterType: 'Job-Specific Coaching',
    relatedAssessmentType: null,
    dueDate: '2026-04-14',
    status: 'in_progress',
    notes:
      'Observe lift setup before deciding whether coaching or assessment is the better next step.',
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'high_risk_area',
      'station',
      'Pallet Build Station',
    ),
    itemType: 'station',
    priorityBucket: 'high_risk_area',
    displayLabel: 'Pallet Build Station',
    employeeName: null,
    employeeId: null,
    stationName: 'Pallet Build Station',
    stationId: 'ST-201',
    sourceReason:
      'Previous walkthroughs flagged repeated trunk rotation, extended reach, and inconsistent reset posture.',
    relatedEncounterType: 'Task Assessments',
    relatedAssessmentType: 'Observational Scan',
    dueDate: '2026-04-14',
    status: 'open',
    notes:
      'Start with behavior scan, then confirm whether workstation height is driving the reach pattern.',
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'worker_uncertain_stiffness_mobility',
      'employee',
      'Marcus Tate',
    ),
    itemType: 'employee',
    priorityBucket: 'worker_uncertain_stiffness_mobility',
    displayLabel: 'Marcus Tate - movement quality check',
    employeeName: 'Marcus Tate',
    employeeId: 'EMP-1231',
    stationName: null,
    stationId: null,
    sourceReason:
      'Observed guarded motion during tote transfer; stiffness or asymmetry still needs clarification.',
    relatedEncounterType: 'Human Movement Assessments',
    relatedAssessmentType: 'Human Movement Assessment',
    dueDate: null,
    status: 'open',
    notes:
      'Keep recommendation-based only for now; do not auto-create an HMA path.',
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'medium_risk_area',
      'station',
      'Receiving Dock',
    ),
    itemType: 'station',
    priorityBucket: 'medium_risk_area',
    displayLabel: 'Receiving Dock',
    employeeName: null,
    employeeId: null,
    stationName: 'Receiving Dock',
    stationId: 'ST-305',
    sourceReason:
      'Moderate repetition and reach demand; needs a simple scan after top employee priorities are handled.',
    relatedEncounterType: 'Safety Coaching',
    relatedAssessmentType: 'Observational Scan',
    dueDate: null,
    status: 'deferred',
    notes: 'Wait until inbound trailer volume settles before running the scan.',
  },
  {
    id: createPrioritizationItemId(
      MOCK_PRIORITIZATION_DATE,
      'low_risk_area',
      'station',
      'Breakroom Restock Route',
    ),
    itemType: 'station',
    priorityBucket: 'low_risk_area',
    displayLabel: 'Breakroom Restock Route',
    employeeName: null,
    employeeId: null,
    stationName: 'Breakroom Restock Route',
    stationId: 'ST-410',
    sourceReason:
      'Lower observed physical demand but still useful for relationship development and spot checks.',
    relatedEncounterType: 'Relationship Development',
    relatedAssessmentType: 'Observational Scan',
    dueDate: null,
    status: 'open',
    notes: null,
  },
];
